config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'top#main'
  get 'top/main'
  resources :cart_items, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :products, through: :cart_items

    
    def add_product(product_id, quantity)
        current_item = cart_items.find_by(product_id: product_id)
        if current_item
          current_item.qty = quantity.to_i # 既存の数量と置き換える
        else
          current_item = cart_items.build(product_id: product_id, qty: quantity.to_i)
        end
        current_item.save
        current_item
    end
    
    def total_price
        cart_items.inject(0) { |sum, item| sum + (item.qty * item.product.price) }
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_cart
    private
    def current_cart
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
  end

  def create
    product = Product.find(params[:product_id])
    quantity = params[:qty].to_i  # 数値に変換する
    @cart_item = current_cart.add_product(product.id, quantity)
    current_cart.save
    if @cart_item.save
      redirect_to cart_path(current_cart), notice: 'カートに商品を追加しました。'
    else
      redirect_to products_path, alert: '商品の追加に失敗しました。'
    end
  end

  def destroy
    @cart_item = current_cart.cart_items.find_by(id: params[:id])
    @cart_item.destroy
    message = 'カートから商品を削除しました'
    redirect_to cart_path(current_cart), notice: message
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = '1レコード追加しました'
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    flash[:notice] = '1レコード削除しました'
    redirect_to products_path
  end
  
  private
  
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/create.html.erb
<h1>CartItems#create</h1>
<p>Find me in app/views/cart_items/create.html.erb</p>

app/views/cart_items/destroy.html.erb
<h1>CartItems#destroy</h1>
<p>Find me in app/views/cart_items/destroy.html.erb</p>

app/views/cart_items/new.html.erb
<h1>CartItems#new</h1>
<p>Find me in app/views/cart_items/new.html.erb</p>


<p>
    <%= @product.name %>
    <%= @product.price %>
    <%= form_with url: cart_items_path, method: :post do |form| %>
        <%= form.number_field :qty, value: 1, min:  1 %>
        <%= form.hidden_field :product_id, value: @product.id %>
        <%= form.submit 'カートに追加' %>
    <% end %>
</p>

app/views/carts/show.html.erb
<h2>ショッピングカート</h2>

<% if current_cart.cart_items.any? %>
  <table>
    <thead>
      <tr>
        <th>商品名</th>
        <th>価格</th>
        <th>数量</th>
        <th>小計</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% current_cart.cart_items.each do |cart_item| %>
        <tr>
          <td><%= cart_item.product.name %></td>
          <td><%= cart_item.product.price %>円</td>
          <td><%= cart_item.qty %>個</td>
          <td><%= cart_item.qty * cart_item.product.price %>円</td>
          <td>
            <%= button_to '削除', cart_item_path(cart_item), method: :delete, data: { confirm: 'この商品をカートから削除しますか？' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="total_price">
    <p>合計金額: <%= number_to_currency(current_cart.total_price, unit: "¥", precision: 0, format: "%n円") %></p>
  </div>




  <%= link_to '購入を進める', products_path%>
<% else %>
  <p>カートに商品がありません。</p>
   <%= link_to '購入を進める', products_path%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>


<h2>商品一覧</h2>
<% @products.each do |e| %>
    <p>
        <%= e.name %>/
        <%= e.price %>円
        <%=link_to '削除', "/products/#{e.id}", data: { turbo_method: :delete } %>
        <%=link_to 'カート追加', new_cart_item_path(product_id: e.id) %>
    </p>
<% end %>

<h2>商品を追加する</h2>
<%=link_to '追加', new_product_path %>

<h2>カートを見る</h2>
<%=link_to 'カートを見る', cart_path(current_cart) %>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

<%= form_for @product , url: {action: :create} do |f| %>
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %></br>
    
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %></br>
    
    <%= f.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>